In [1]:
from utils import setrootdir
setrootdir("ppgcc-coautorias")

'Directory ppgcc-coautorias successfully loaded as current working directory.'

In [2]:
import os

from dotenv import load_dotenv

from src.preprocessing import Preprocesser

In [3]:
load_dotenv()

DATASET_DIRECTORY = os.getenv("DATASET_DIRECTORY")
METADATA_FILE = os.getenv("METADATA_FILE")

# 2. Preprocessing

In [4]:
preprocesser = Preprocesser(
    data_dir=DATASET_DIRECTORY,
    metadata_file=METADATA_FILE,
    step_directory="02-preprocessing",
)

## 2.1. DataFrames construction

In [5]:
institution_registry = preprocesser.extract_institution_registry(
    selection_dir_name="01-selection"
)

institution_registry

InstitutionRegistry
- Institutions: 67
- Total researchers: 1810
- Researchers per institution:
	- Average: 27.01
	- Median: 23
	- P25: 15.0, P75: 32.0
- Largest: UFPE (89)
- Smallest: UERN (7)
- Top 3 institutions: UFPE (89), USP-SC (77), UFMG (66)

### 2.1.1. Productions

In [6]:
df_productions = preprocesser.frame_productions_all_institutions(institution_registry)
df_productions

,name,citation,lattes_id,institution,production,authors,location,type,year,issn
0,Jose Maria Nazar David,"[Jose Maria Nazar David, DAVID, JOSE MARIA, DA...",3640497501056163,UFJF,Designing collaboration through a web-based gr...,"[Jose Maria Nazar David, Marcos R. S. Borges]",International Journal of Computer Applications...,PERIODICO,2004,09528091
1,Jose Maria Nazar David,"[Jose Maria Nazar David, DAVID, JOSE MARIA, DA...",3640497501056163,UFJF,Supporting Awareness in Groupware through an A...,"[Rita Suzana Pitangueira Maciel, Jose Maria Na...",JOURNAL OF UNIVERSAL COMPUTER SCIENCE,PERIODICO,2009,0948695X
2,Jose Maria Nazar David,"[Jose Maria Nazar David, DAVID, JOSE MARIA, DA...",3640497501056163,UFJF,Management of Scientific Experiments in Comput...,"[Regina Maria Maciel Braga, Fernanda Cláudia A...",iSys - Revista Brasileira de Sistemas de Infor...,PERIODICO,2012,19842902
3,Jose Maria Nazar David,"[Jose Maria Nazar David, DAVID, JOSE MARIA, DA...",3640497501056163,UFJF,Scientific Provenance Metadata Capture and Man...,"[Wander Gaspar, Regina Maria Maciel Braga, Fer...","International Journal of Metadata, Semantics a...",PERIODICO,2015,17442621
4,Jose Maria Nazar David,"[Jose Maria Nazar David, DAVID, JOSE MARIA, DA...",3640497501056163,UFJF,PERSONNA: proposta de ontologia de contexto e ...,"[Paulo Rezende, Crystiam Kelle Pereira, Fernan...",Revista Brasileira de Informática na Educação,PERIODICO,2015,14145685
...,...,...,...,...,...,...,...,...,...,...
230926,Leandro Santiago de Araujo,"[Leandro Santiago de Araujo, L. S. ARAUJO, LEA...",6358983442870515,UFF,Pruning Weightless Neural Networks,"[Zachary Susskind, Igor Dantas Dos Santos Mira...",30th European Symposium on Artificial Neural N...,CONFERENCIA,2022,None
230927,Leandro Santiago de Araujo,"[Leandro Santiago de Araujo, L. S. ARAUJO, LEA...",6358983442870515,UFF,GSink - A Runtime for Gamma Programs and its C...,"[MELLO, RUI R., PAILLARD, GABRIEL A. L., Leand...",2023 IEEE International Parallel and Distribut...,CONFERENCIA,2023,None
230928,Leandro Santiago de Araujo,"[Leandro Santiago de Araujo, L. S. ARAUJO, LEA...",6358983442870515,UFF,Heuristics for t-admissibility with complex ne...,"[Carlos Thadeu Duarte Santos, Anderson Zudio, ...",SBPO 2023: Simpósio Brasileiro de Pesquisa Ope...,CONFERENCIA,2023,None
230929,Leandro Santiago de Araujo,"[Leandro Santiago de Araujo, L. S. ARAUJO, LEA...",6358983442870515,UFF,Gerando base de grafos não isomorfos com seus ...,"[Felipe Souza, Leandro Santiago de Araujo, Luí...",SBPO 2023: Simpósio Brasileiro de Pesquisa Ope...,CONFERENCIA,2023,None
230930,Leandro Santiago de Araujo,"[Leandro Santiago de Araujo, L. S. ARAUJO, LEA...",6358983442870515,UFF,Paralelismo e Heurísticas para o problema da m...,"[Thiago Lopes Nascimento, Fábio Protti, Luís F...",SBPO 2023: Simpósio Brasileiro de Pesquisa Ope...,CONFERENCIA,2023,None

## 2.2. Production IDs

In [7]:
df_productions["production"] = df_productions["production"].str.upper()

In [9]:
unique_productions = sorted(list(df_productions["production"].unique()))
unique_productions

['                HALITE                DS</SUB>              </I>              : FAST AND SCALABLE SUBSPACE CLUSTERING FOR MULTIDIMENSIONAL DATA STREAMS',
 '#CHI4BETTER4WHOM?',
 '#DEOLHONOSCORAIS: A POLYGONAL ANNOTATED DATASET TO OPTIMIZE CORAL MONITORING',
 '#FIQUEEMCASA, MAS SE MANTENHA ENSINANDO-APRENDENDO: ALGUMAS QUESTÕES EDUCACIONAIS EM TEMPOS DE PANDEMIA',
 '#INOVAREAPRENDER: O USO DA ROBÓTICA EDUCACIONAL NO PROCESSO DE APRENDIZAGEM SIGNIFICATIVA ENVOLVENDO EDUCAÇÃO BÁSICA E ENSINO SUPERIOR',
 '#PRACEGOVER: A LARGE DATASET FOR IMAGE CAPTIONING IN PORTUGUESE',
 '#PRACEGOVER: INVESTIGATING THE DESCRIPTION OF VISUAL CONTENT IN BRAZILIAN ONLINE SOCIAL MEDIA',
 '#RURALCONTRAAEDES: PLATAFORMA DE  MONITORAMENTO ONLINE DE FOCOS  DO MOSQUITO AEDES AEGYPIT  XXI ENAPET 2016: ENCONTRO NACIONAL DE GRUPOS PET',
 '#RURALCONTRACORONA: UMA PLATAFORMA DE APOIO À DIFUSÃO DE AÇÕES CONTRA COVID-19 NO ÂMBITO DA BAIXADA FLUMINENSE',
 '#STAYHOME: MONITORING SOCIAL DISTANCING TRENDS IN AMAZONAS DURING THE COVID-19 PANDEMIC USING GOOGLE MOBILE DATA',
 '#TEAMINF AT SEMEVAL-2018 TASK 2: EMOJI PREDICTION IN TWEETS',
 '#TWINTERA!: A SOCIAL MATCHING ENVIRONMENT BASED ON MICROBLOGGING',
 '#WASHTHEHATE: UNDERSTANDING THE PREVALENCE OF ANTI-ASIAN PREJUDICE ON TWITTER DURING THE COVID-19 PANDEMIC',
 '#WORLDCUP2014 ON TWITTER',
 '$$S^2FS$$: SINGLE SCORE FEATURE SELECTION APPLIED TO THE PROBLEM OF DISTINGUISHING LONG NON-CODING RNAS FROM PROTEIN CODING TRANSCRIPTS',
 '$${IN_K}$$ : A NON-FREGEAN LOGIC OF EXPLICIT KNOWLEDGE',
 '$${LAMBDA }$$ &#955; -LGP: AN IMPROVED VERSION OF LINEAR GENETIC PROGRAMMING EVALUATED IN THE ANT TRAIL PROBLEM',
 '$C^{\\AL}$-CLASSICAL SOLUTIONS FOR AN  ABSTRACT   NON-AUTONOMOUS   INTEGRO-DIFFERENTIAL EQUATIONS.',
 '$DC_{F}$-INTEGRALS: GENERALIZING C$_{F}$-INTEGRALS BY MEANS OF RESTRICTED DISSIMILARITY FUNCTIONS',
 '$IN_I$ : AN INTUITIONISTIC LOGIC WITHOUT FREGEAN AXIOM AND WITH PREDICATES FOR TRUTH AND FALSITY',
 '$MATHCAL{IMA}$ - $MATHCAL{CID}$ : AN INTEGRATED MODELING APPROACH FOR DEVELOPING EDUCATIONAL MODULES',
 '$O(N)$ TIME ALGORITHMS FOR DOMINATING INDUCED MATCHING PROBLEMS',
 "&#22522;&#20110;&#22797;&#26434;&#32593;&#32476;&#30340;&#26426;&#22120;&#23398;&#20064;&#26041;&#27861; (CHINESE VERSION OF THE BOOK 'MACHINE LEARNING IN COMPLEX NETWORKS')",
 '&#61623; ANÁLISE DE ROBUSTEZ DAS MARCAS D?ÁGUA NO DOMÍNIO ESPACIAL',
 '&#61623; MARCA D?ÁGUA INSERÇÃO E ATAQUE',
 '&#61713; USING INFORMATION TECHNOLOGY FOR PERSONALIZING THE COMPUTER SCIENCE TEACHING',
 '&#65279;&#65279;&#65279;AGREGAÇÃO DE PACOTES EM AMBIENTES COM ENLACES DE BAIXA CAPACIDADE DE TRANSMISSÃO',
 '&#8203; IMPLEMENTAÇÃO PARALELA DE ALGORITMOS DE CLASSIFICAÇÃO DE  DADOS PARA UMA DSL DE VISUALIZAÇÃO DE DADOS GEO\xadESPACIAIS',
 '&#8203;BAYESIAN OPTIMIZATION FOR PATH PLANNING OF UAVS IN MONITORING APPLICATIONS',
 '&#8206;ON GENERALIZED MIXTURE FUNCTIONS',
 '&#8459;&#8734;-FILTERING DESIGN FOR DISCRETE-TIME MARKOV JUMP SYSTEMS WITH HIDDEN PARAMETERS',
 '&#945; -LABELLINGS OF LOBSTERS WITH MAXIMUM DEGREE THREE',
 '&#945;-DIPERFECT DIGRAPHS',
 '&#945;-IDEALS OF FUZZY LATTICES',
 '&#946;3-IRT: A NEW ITEM RESPONSE MODEL AND ITS APPLICATIONS',
 '&#946;CAMKII REGULATES BIDIRECTIONAL LONG-TERM PLASTICITY IN CEREBELLAR PURKINJE CELLS BY A CAMKII/PP2B SWITCH MECHANISM',
 '&#954;-ENTROPY BASED RESTRICTED BOLTZMANN MACHINES',
 '&#956;SDN: AN SDN-BASED ROUTING ARCHITECTURE FOR WIRELESS SENSOR NETWORKS',
 '&#956;TESLA PROTOCOL IN VEHICULAR NETWORKS',
 '&#960;SOD-M: BUILDING SOC APPLICATIONS IN THE PRESENCE OF NON-FUNCTIONAL REQUIREMENTS',
 '&#967;-DIPERFECT DIGRAPHS',
 '&#969;-IVE METHODOLOGY: ADMISSIBLE INTERLEAVING ENTROPY METHODS APPLIED TO VIDEO STREAMING TRAFFIC CLASSIFICATION',
 '&LT;TITLE&GT;A NEW METHOD TO EFFICIENTLY REDUCE HISTOGRAM DIMENSIONALITY&LT;/TITLE&GT;',
 '&LT;TITLE&GT;A UNIFYING GRAPH-CUT IMAGE SEGMENTATION FRAMEWORK: ALGORITHMS IT ENCOMPASSES AND EQUIVALENCES AMONG THEM&LT;/TITLE&GT;',
 '&LT;TITLE&GT;AUTOMATIC ANATOMY RECOGNITION VIA FUZZY OBJECT MODELS&LT;/TITLE&GT;',
 '&LT;TITLE&GT;DEPOLARIZATION BEHAVIOR OF MULTIPLE SCATTERED LIGHT FROM AN OPTICALLY DENSE RANDOM MEDIUM&LT;/TITLE&GT;',
 '&LT;TITLE&GT;NONLINEAR FEATURES EXTRACTION APPLIED TO POLLEN GRAIN IMAGES&LT;/TITLE&GT;',
 '&LT;TITLE&GT;SIMULINK TOOLBOX FOR SIMULATION AND ANALYSIS OF OPTICAL FIBER LINKS&LT;/TITLE&GT;',
 '&LT;TITLE&GT;TOWARD A PERCEPTION AND SENSOR FUSION ARCHITECTURE FOR A ROBOTIC AIRSHIP&LT;/TITLE&GT;',
 '&QUOT; DADOS PRELIMINARES NO ESTUDO DA OSCILAÇÃO CORPORAL EM VOLUNTÁRIOS HÍGIDOS&QUOT;',
 '&QUOT;APERTA O PLAY!&QUOT; ANÁLISE DA INTERAÇÃO EXPLORATÓRIA EM UM JOGO BASEADO EM PENSAMENTO COMPUTACIONAL',
 '&QUOT;CLINICAL DEMENTIA RATING SCORE PREDICTION BASED ON AUTOMATED BRAIN IMAGE SEGMENTATION',
 '&QUOT;EFFICIENT ALGORITHMS FOR THE HOTLINK ASSIGNMENT PROBLEM: THE WORST CASE SEARCH&QUOT;',
 '&QUOT;EXTRAÇÃO E ANÁLISE DE CARACTERÍSTICAS EM TERMOGRAMAS PARA AUXÍLIO AO DIAGNÓSTICO DE CÂNCER DE MAMA',
 '&QUOT;FUI CONTRATADO PARA ENSINAR COMPUTAÇÃO!&QUOT;: UM OLHAR SOBRE A SUPOSTA NEUTRALIDADE POLÍTICO-PEDAGÓGICA DO PROFESSOR UNIVERSITÁRIO DE COMPUTAÇÃO NO BRASIL',
 '&QUOT;GREEDY APPROACH FOR IMAGE RESTORATION BASED ON ENERGY MINIMIZATION&QUOT;',
 '&QUOT;IS ANYBODY THERE?&QUOT;',
 '&QUOT;KEEP IT SIMPLE, LAZY&QUOT; -- METALAZY: A NEW METASTRATEGY FOR LAZY TEXT CLASSIFICATION',
 '&QUOT;PERFORMANCE EVALUATION OF DISTRIBUTION IN OODBMS: A CASE STUDY WITH O2&QUOT;',
 '&QUOT;POLUIÇÃO EM REDES SOCIAIS DE DISTRIBUIÇÃO DE VIDEOS',
 '&QUOT;THE MAGIC OF SCIENCE:&QUOT; BEYOND ACTION, A CASE STUDY ON LEARNING THROUGH SOCIOENACTION',
 '&QUOT;THIS CONVERSATION WILL BE RECORDED&QUOT;: AUTOMATICALLY GENERATING INTERACTIVE DOCUMENTS FROM CAPTURED MEDIA',
 '&QUOT;TODAY IS SO COOL NOBODY WANTS TO LEAVE&QUOT;: WHAT MAKES TEENAGERS ENGAGED IN DEVELOPING EDUCATIONAL GAMES AT SCHOOL?',
 '&QUOT;TWO-STAGE BINARY IMAGE OPERATOR DESIGN: AN APPROACH BASED ON INTERACTION INFORMATION&QUOT;',
 '&QUOT;UM FRAMEWORK PARA O DESENVOLVIMENTO DE AGENTES COGNITIVOS EM JOGOS DE PRIMEIRA PESSOA.&QUOT;',
 '&QUOT;UMA ABORDAGEM HÍBRIDA, BASEADA EM METAHEURÍSTICAS E NA HEURÍSTICA GENIUS, APLICADA AO PROBLEMA DE ROTEAMENTO DE VEÍCULOS COM COLETA E ENTREGA SIMULTÂNEA&QUOT;',
 '&QUOT;UMA HEURISTICA EFICIENTE PARA PROBLEMAS DE ROTEAMENTO DE VEÍCULOS&QUOT;',
 '&QUOT;UN OUTIL GÉNÉRIQUE DE GESTION PAR POLITIQUES: VALIDATION DE L?IMPLÉMENTATION DANS UN RÉSEAU SANS FILS WLAN',
 '&QUOT;WEEPING ANGEL&QUOT;: BIBLIOTECA CROSS PLATAFORM DE BAIXO CUSTO PARA DETECÇÃO DE ATENÇÃO EM DISPOSITIVOS MÓVEIS',
 '&QUOT;WHIZKEY: A WIZARD-BASED TOOL FOR INSTALLING DIGITAL LIBRARIES',
 "'$\\ALPHA$-DIPERFECT DIGRAPHS'",
 "''AEDES VS. REPELLENTS'': APPLYING TOWER DEFENSE DYNAMICS IN A DIGITAL GAME TO COMBAT THE MOSQUITO",
 "''DESATENTOS'': UMA PROPOSTA DE JOGO DIGITAL PARA CONSCIENTIZAÇÃO DE SINTOMAS PRESENTES EM PORTADORES DO TDAH",
 "'A COMPARISON OF DEEP LEARNING-BASED VISUAL ODOMETRY ALGORITHMS IN CHALLENGING SCENARIOS",
 "'A MULTI-AGENT CYCLIC PATROLLING OF NODES STRATEGY ON DYNAMIC EDGE WEIGHTS GRAPHS'",
 "'A MULTI-AGENT EDGE PATROLLING ON DYNAMIC EDGE WEIGHTS EULERIAN GRAPHS'",
 "'A NOVA ELETRICIDADE': APLICAÇÕES, CHOQUES E TENDÊNCIAS DA IA MODERNA",
 "'A ÚLTIMA ÁRVORE' DIGITAL: A IMPLEMENTAÇÃO DE UM JOGO EDUCACIONAL QUE UTILIZA MÉTODOS FORMAIS PARA ESTIMULAR O PENSAMENTO COMPUTACIONAL",
 "'A ÚLTIMA ÁRVORE: A CHEGADA DA FAZENDA?, APLICANDO GRAMÁTICA DE GRAFOS COM ATRIBUTOS AO DESENVOLVIMENTO DO PENSAMENTO COMPUTACIONAL",
 "'A ÚLTIMA ÁRVORE: O POVO DA CIDADE', UTILIZANDO A CONDIÇÃO NEGATIVA DE APLICAÇÃO EM UM JOGO EDUCACIONAL",
 "'ALIGNING BUSINESS REQUIREMENTS WITH SERVICES  QUALITY CHARACTERISTICS BY USING LOGICAL ARCHITECTURES.'",
 "'ALL THE THINGS THAT COME AND GO, STOP AND SAY HELLO': TOWARDS AN ONTOLOGICAL ACCOUNT OF HOW PARTICIPANTS ENTER AND EXIT EVENTS",
 "'AN APPROACH FOR LEARNING AND CONSTRUCTION OF EXPRESSIVE ONTOLOGY FROM TEXT IN NATURAL LANGUAGE'",
 "'AN ONTOLOGY ANALYSIS IMPLEMENTATION IN CONSTRAINT LOGIC PROGRAMMING'",
 "'BATALHA DA VIZINHANÇA'': UM JOGO DE TABULEIRO PARA O COMBATE A DENGUE",
 "'BDD ASSEMBLE!': A PAPER-BASED GAME PROPOSAL FOR BEHAVIOR DRIVEN DEVELOPMENT DESIGN LEARNING",
 "'BN ANATOMY' AN INTERACTIVE AUGMENTED REALITY SYSTEM FOR LEARNING BONE ANATOMY",
 "'C. B. (2021, OCTOBER). APRENDIZAGEM BASEADA EM JOGOS PARA CELULAR COM O APLICATIVO OPI: LIÇÕES APRENDIDAS COM UMA AVALIAÇÃO DE USABILIDADE PARA CRIANÇAS",
 "'DEDUPLICATING LARGE VOLUMES OF DATA FROM NATURAL AND LEGAL ENTITIES IN THE GOVERNMENTAL FIELD",
 "'DISPOSITIVO PARA COLETA E PROCESSAMENTO DE SINAIS CEREBRAIS E SUA INTEGRAÇÃO A CADEIRA DE RODAS",
 "'EU TAMBÉM QUERO JOGAR!' - REAVALIANDO AS PRÁTICAS E DIRETRIZES DE ACESSIBILIDADE EM JOGOS",
 "'EVERY MOVE YOU MAKE IN EVERY GAME YOU PLAY': CAN GAME LOGS DETERMINE PLAYER'S ENGAGEMENT?",
 "'EVERYTHING I DISAGREE WITH IS #FAKENEWS': CORRELATING POLITICAL POLARIZATION AND SPREAD OF MISINFORMATION",
 "'EXPLORING A THREE-DIMENSIONAL, REQUIREMENTS- BASED, BALANCED SCORECARD BUSINESS MODEL.'",
 "'FLASH DETECTION': WHAT CAN YOU SEE IN RAPIDLY DISPLAYED IMAGES?",
 "'FUZZY LOGIC SYSTEM MODELING ASIAN SOYBEAN RUST MONOCYCLIC PROCESS'",
 "'GLOBAL MULTIPLE ALIGNMENT BASED ON PROFILE AND AGGLOMERATIVE SINGLE-LINK CLUSTERING: A COMPARATIVE STUDY WITH CLUSTAL-W (EMBL-EBI) TOOL'",
 "'HYDRONODE: A LOW COST, ENERGY EFFICIENT, MULTI PURPOSE NODE FOR UNDERWATER SENSOR NETWORKS'",
 "'IMPLEMENTING COFFEE RUST NEURO-FUZZY MODEL THROUGH GEOSCIENCE'",
 "'IMPLEMENTING SOYBEAN RUST FUZZY LOGIC SYSTEM MODEL THROUGH GEOSCIENCE'",
 "'IS LEARNING TO RANK WORTH IT?  A STATISTICAL ANALYSIS OF LEARNING TO RANK METHODS",
 "'JOVENS PROGRAMADORES' NA PANDEMIA",
 "'JOVENS PROGRAMADORES' NA PANDEMIA: ENSINO DE PROGRAMAÇÃO DE COMPUTADORES DE FORMA REMOTA",
 "'JUNTOS VENCEREMOS' ? UM EXERGAME PARA TESTE DE JOGO MULTIPLAYER UTILIZANDO VISÃO COMPUTACIONAL",
 "'JUNTOS VENCEREMOS' UM EXERGAME PARA TESTE DE JOGO MULTIPLAYER UTILIZANDO VISÃO COMPUTACIONAL",
 "'KEEP IT SIMPLE, LAZY' -- METALAZY: A NEW METASTRATEGY FOR LAZY TEXT CLASSIFICATION",
 "'LOOKS GOOD TO ME ;-)': ASSESSING SENTIMENT ANALYSIS TOOLS FOR PULL REQUEST DISCUSSIONS",
 "'MERGE SOURCE CODING'",
 "'MODELING AND SCHEDULING HARD REAL-TIME BIOMEDICAL SYSTEMS WITH TIMING AND ENERGY CONSTRAINTS - QUALIS: A. CIRCULAÇÃO: INTERNACIONAL.",
 "'MORO NUM PAÍS TROPICAL': A CRISE POLÍTICA BRASILEIRA E HUMOR NO TWITTER",
 "'MY LIFE DOESN'T HAVE TO BE AN OPEN BOOK': A MODEL TO HELP DESIGNERS TO ENHANCE PRIVACY CONTROLS ON SOCIAL NETWORK SITES",
 "'NEURO-FUZZY MODELING COFFEE RUST MONOCYCLIC PROCESS'",
 "'NO CODE ANOMALY IS AN ISLAND' -- ANOMALY AGGLOMERATION AS SIGN OF PRODUCT LINE INSTABILITIES",
 "'NÃO QUEIMA MEU LED!' - UM JOGO DE REALIDADE VIRTUAL PARA O ENSINO DE CIRCUITOS DIGITAIS",
 "'O COMPUTADOR COMO INSTRUMENTO AUXILIAR DE ENSINO.",
 "'O USO DO CLASSROOM COMO RECURSO EDUCACIONAL NA EDUCAÇÃO DE JOVENS E ADULTOS",
 "'P-MEDIAN AND P-CENTER APPLIED TO COLOR QUANTIZATION AND PIXEL MAPPING'",
 "'PROCESSO DE PLANEJAMENTO PARA PRODUÇÃO, EXECUÇÃO E AVALIAÇÃO DE CONTEÚDOS CROSSMIDIÁTICOS, EDUCATIVOS E TELEVISIVOS",
 "'RADIATION-INDUCED ERROR CRITICALITY IN MODERN HPC PARALLEL ACCELERATORS",
 "'SISTEMA DE RECONHECIMENTO FACIAL PARA CONTROLO AUTOMÁTICO DE PRESENÇA EM SALA DE AULAS'",
 "'SIX-WRITINGS' MULTIMODAL PROCESSING WITH PICTOPHONETIC CODING TO ENHANCE CHINESE LANGUAGE MODELS",
 "'STRESS LEVEL OF CRITICAL CARE NURSES: EVALUATION BY HEART RATE VARIABILITY'",
 "'TÉCNICAS DE APRENDIZADO PROFUNDO PARA AUXÍLIO NA DETECÇÃO DO COVID-19 EM IMAGENS DE RAIOS-X DO TÓRAX'",
 "'UAI! QUE ISSO SÔ!': CONHECENDO O 'MINEIRÊS' ATRAVÉS DE UM JOGO DIGITAL",
 "'ULTIMATE FOOD DEFENSE': A SERIOUS GAME FOR HEALTHY EATING BEHAVIOR AWARENESS",
 "'UMA HEURÍSTICA BASEADA NO MÉTODO DE BUSCA A* APLICADA AO PROBLEMA DE ROTEAMENTO'",
 "'UNIVERSITY UNIVERSE': A MOBILE GAME TO SIMULATE THE UNIVERSITY STUDENT LIFE",
 "'VALUES AT PLAY - BRASIL' AVALIAÇÃO DE ARTEFATO",
 "'VIDA DE ES': PROTÓTIPO DE UM JOGO DE CARTAS PARA O ENSINO DE SITUAÇÕES PRÁTICAS VIVENCIADAS POR UM ENGENHEIRO DE SOFTWARE",
 "'VIDEO POLLUTION ON THE WEB''",
 "'YOU?RE ON A BICYCLE WITH A LITTLE MOTOR': BENEFITS AND CHALLENGES OF USING AI CODE ASSISTANTS",
 "'É PRA FAZER O QUE, PROFESSORA?' FOMENTANDO INICIATIVA E INOVAÇÃO NA DISCIPLINA DE IHM",
 '(2A ED.) O BEIJO DE JULIANA: QUATRO FÍSICOS TEÓRICOS CONVERSAM SOBRE CRIANÇAS, CIÊNCIAS DA COMPLEXIDADE, BIOLOGIA, POLÍTICA, RELIGIÃO E FUTEBOL...',
 '(3,4,6)-FULLERENES GRAPHS',
 '(ARTIGO CONVIDADO PELA COMISSAO ORGANIZADORA)TUTOR BEHAVIOUR IN A MULTI-AGENT ITS GUIDED THROUGH MENTAL STATES ACTIVITIES',
 '(ARTIGO SOBRE A DISSERTAÇÃO:) SISTEMA BIOMÉDICO PARA AVALIAÇÃO E REABILITAÇÃO MOTORA EM HEMIPARÉTICOS POR AVC',
 '(AUTO) SINTONIA-FINA EM SISTEMAS DE BANCOS DE DADOS NAS ORGANIZAÇÕES',
 '(BEST PAPER) REDES AUTO-RECONFIGURÁVEIS RANDOMIZADAS PARA COMUNICAÇÃO DISTRIBUÍDA EM DATACENTERS',
 '(BR-SCMM) BRAZILIAN SMART CITY MATURITY MODEL: A PERSPECTIVE FROM THE HEALTH DOMAIN',
 '(CAUSAL/INTERPRETATIVE UNDERSTANDING), (LAW-GOVERNED DESCRIPTION/PREDICTION), AND EMPIRICAL LEGAL STUDIES: COMMENT',
 '(CHAR)LAR: UMA EXPERIMENTAC&#807;A&#771;O DE GERAC&#807;A&#771;O DE POEMAS BASEADA EM REDES NEURAIS RECORRENTES',
 '(CHAR)LAR: UMA EXPERIMENTAÇÃO DE GERAÇÃO DE POEMAS BASEADA EM REDES NEURAIS RECORRENTES',
 '(CIA)&LT;SUP&GT;2&LT;/SUP&GT;-ITS: INTERCONNECTING MOBILE AND UBIQUITOUS DEVICES FOR INTELLIGENT TRANSPORTATION SYSTEMS',
 '(CIA)2-ITS: INTERCONNECTING MOBILE AND UBIQUITOUS DEVICES FOR INTELLIGENT TRANSPORTATION SYSTEMS',
 '(CIA)2</SUP>-ITS: INTERCONNECTING MOBILE AND UBIQUITOUS DEVICES FOR INTELLIGENT TRANSPORTATION SYSTEMS',
 '(DE) CONSTRUCTING BIAS ON SKIN LESION DATASETS',
 '(DEEP) LEARNING FROM FRAMES',
 '(DOI 10.5753/CBIE.SBIE.2007.155-158) CARACTERIZAÇÃO DAS ÊNFASES DE EDUCAÇÃO E TREINAMENTO EM AMBIENTES VIRTUAIS 3D',
 '(DOI: 10.1007/978-3-319-31307-8_8) SERIOUS GAMES FOR BALANCE IMPROVEMENT: A SYSTEMATIC LITERATURE MAPPING',
 '(DOI:10.1007/978-3-319-31307-8_25) DIGITAL GAMES FOR MATH LITERACY: A SYSTEMATIC LITERATURE MAPPING ON BRAZILIAN PUBLICATIONS',
 "(ETNO) INFORMÁTICA NA EDUCAÇÃO: USO N'SAMAT COMO ORGANIZADOR PRÉVIO PARA AUXILIAR NA APRENDIZAGEM DE ARITMÉTICA EM TRÊS ESCOLAS MOÇAMBICANAS.",
 '(IN)SEGURANÇA DO VOTO ELETRÔNICO NO BRASIL',
 '(INTER)DISCIPLINARIDADE E TRANSVERSALIDADES: O PROJETO DE FORMAÇÃO SUPERIOR DA UNIVERSIDADE FEDERAL DO ABC',
 '(K, L)-SANDWICH PROBLEM: WHY NOT ASK FOR SPECIAL KINDS OF BREAD?',
 '(K,L)-P_4-SPARSE GRAPHS (POSTER)',
 '(K,L)-SANDWICH PROBLEM: WHY NOT ASK FOR SPECIAL KINDS OF BREAD?',
 '(K,L)-SANDWICH PROBLEMS: WHY NOT ASK FOR SPECIAL KINDS OF BREAD?',
 '(K,L)-SANDWICH PROBLEMS: WHY NOT ASK FOR SPECIAL KINDS OF BREAD?.',
 '(L,U)-BOUNDED PRIORITY QUEUES',
 '(M,K)-GUR GAME: EXPLOITING MESSAGE DISCARDS IN ORDER TO INCREASE THE LIFETIME AND SPATIAL DIVERSITY IN AUTONOMIC WIRELESS SENSOR NETWORKS',
 '(META)MODELAGEM DE ESPAÇOS INTELIGENTES PESSOAIS E ESPAÇOS INTELIGENTES FIXOS PARA APLICAÇÕES UBÍQUAS',
 '(MICRO)CELL COVERAGE AREA USING STATISTICAL METHODS',
 '(MINISYMPOSIUM INVITED TALK) BLOCK COORDINATE DESCENT FOR SMOOTH NONCONVEX CONSTRAINED MINIMIZATION',
 '(MINISYMPOSIUM INVITED TALK) ERNESTO BLOCK COORDINATE DESCENT AND THE CLOSE ENOUGH TRAVELING SALESMAN PROBLEM',
 '(MIS)INFORMATION DISSEMINATION IN WHATSAPP: GATHERING, ANALYZING AND COUNTERMEASURES',
 '(NO PRELO DA EDITORA)PROPRIEDADE INTELECTUAL, EMPREENDEDORISMO E BUSCA DE INFORMAÇÃO TECNOLÓGICA PARA A INFORMÁTICA NA EDUCAÇÃO',
 '(NON-) HOMOMORPHIC APPROACHES TO DENOISE INTENSITY SAR IMAGES WITH NON-LOCAL MEANS AND STOCHASTIC DISTANCES',
 '(N¿, T, N)-IMPLICATIONS',
 '(ORCHIDEA) UMA PRIMEIRA APLICAÇÃO PARA PRÁTICAS MUSICAIS COLETIVAS NA ORQUESTRA DE IDEIAS',
 '(PLENARY TALK) AUGMENTED LAGRANGIAN METHODS: COMPLEXITY AND PERFORMANCE',
 '(PLENARY TALK) COMPLEXITY RESULTS IN NONLINEAR OPTIMIZATION',
 '(PLENARY TALK) CURRENT WORK IN THE DEVELOPMENT OF AUGMENTED LAGRANGIAN SOFTWARE',
 '(PLENARY TALK) PRACTICAL AUGMENTED LAGRANGIAN METHODS',
 '(PLENARY TALK) SAFEGUARDED AUGMENTED LAGRANGIAN METHODS FOR NONCONVEX OPTIMIZATION: CONVERGENCE, COMPLEXITY AND EXPERIMENTS',
 '(RE) CONHECENDO A UNIVERSIDADE DE SÃO PAULO - CONTRIBUIÇÕES DO ENSINO, DA PESQUISA E DA EXTENSÃO NO CAMPO DAS DEFICIÊNCIAS',
 '(RE) CONHECENDO A USP: CONTRIBUIÇÕES DO ENSINO, DA PESQUISA E DA EXTENSÃO NO CAMPO DAS DEFICIÊNCIAS',
 '(RE)ACTIVE LOAD CONTROL BASED ON RADIO LINK QUALITY FOR THE UMTS/WCDMA FORWARD LINK',
 '(RE)CONFIGURATION ALGORITHMS FOR PEER-TO-PEER OVER AD HOC NETWORKS',
 '(RE)CONHECENDO A USP - CONTRIBUIÇÕES DA PESQUISA E DA EXTENSÃO NO CAMPO DAS DEFICIÊNCIAS: CURSOS PRESENTES',
 '(RE)EVALUATING THE INFLUENCE OF CONTEXTUALIZED EXAMPLES IN TEACHING AN INTRODUCTORY SOFTWARE ENGINEERING COURSE IN BRAZIL',
 '(RE-) CONFIGURABLE REAL-TIME OPERATING SYSTEMS AND THEIR APPLICATIONS',
 '(REQUIREMENT) EVOLUTION REQUIREMENTS FOR ADAPTIVE SYSTEMS',
 '(RESUMO) EXPRESSIVENESS AND DEFINABILITY IN CIRCUNSCRIPTION',
 '(RESUMO) SCHEMATIC RULES IN NATURAL DEDUCTION FOR LOGIC WITH MODAL OPERATORS',
 '(S,N)-IMPLICATIONS ON BOUNDED LATTICES',
 '(STAR, K)-COLOURINGS OF GRAPHS WITH BOUNDED TREEWIDTH',
 '(T, N)-IMPLICATIONS',
 '(T, N)-IMPLICATIONS AND SOME FUNCTIONAL EQUATIONS',
 '(TEAM DESCRIPTION PAPER) SISTEMA DA ESQUIPE DE FUTEBOL DE ROBÔS ARARABOTS AZUL',
 '(WIP) TASKS SELECTION POLICIES FOR SECURING SENSITIVE DATA ON WORKFLOW SCHEDULING IN CLOUDS',
 '(XOR) XBRL-OBJETO-RELACIONAL: UM FRAMEWORK PARA EXTRAÇÃO, TRANSFORMAÇÃO, CARGA E AUDITORIA DE DADOS FINANCEIROS EM BASES RELACIONAIS E INSTÂNCIAS XBRL',
 ', A SCORING TOOL FOR BOUNDARY DETERMINATION BETWEEN REPETITIVE AND NON-REPETITIVE PROTEIN SEQUENCES',
 ', DESENVOLVIMENTO DE UM SISTEMA GRÁFICO INTERATIVO PARA MODELAGEM E ANIMAÇÃO FACIAL',
 '- 2 -NORM FEATURE LEAST MEAN SQUARE ALGORITHM',
 '- O USO DE PROJETOS-PILOTO. CARACTERIZAÇÃO DO ESTADO DA PRÁTICA DAS ATIVIDADES DE TESTE EM UM CENÁRIO DE DESENVOLVIMENTO DE SOFTWARE BRASILEIRO',
 '- TRANSMISSION POWER CONTROL IN MAC PROTOCOLS FOR WIRELESS SENSOR NETWORKS',
 '--HOMOGENEOUS FUNCTIONS AND A GENERALIZATION OF DIRECTIONAL MONOTONICITY',
 '-ASYMPTOTICALLY PERIODIC SOLUTIONS FOR ABSTRACT EQUATIONS WITH STATE-DEPENDENT DELAY',
 '-BRAZILIAN STYLE SCIENCE--AN ANALYSIS OF THE DIFFERENCE BETWEEN BRAZILIAN AND INTERNATIONAL COMPUTER SCIENCE DEPARTMENTS AND GRADUATE PROGRAMS USING SOCIAL NETWORKS ANALYSIS AND BIBLIOMETRICS',
 '-COLORING OF TIGHT GRAPHS',
 '-CONVEXITY ON GRAPHS WITH DIAMETER TWO: COMPUTING HULL AND INTERVAL NUMBERS',
 '-EU FIZ MEU GAME-: UM FRAMEWORK PARA DESENVOLVIMENTO DE JOGOS POR CRIANÇAS',
 '-FILTERING FOR MARKOV JUMP LINEAR SYSTEMS WITH PARTIAL INFORMATION ON THE JUMP PARAMETER',
 '-FIXING THE CURSE OF THE BAD PRODUCT DESCRIPTIONS- - SEARCH-BOOSTED TAG RECOMMENDATION FOR E-COMMERCE PRODUCTS',
 '-FREE- AS IN FREEDOM TO PROTEST?',
 '-GROUPING FUNCTIONS: A GENERALIZATION OF BIVARIATE GROUPING FUNCTIONS BY                            -CONORMS',
 '-NEAREST NEIGHBOR REGRESSION IN THE ESTIMATION OF TRUNK VOLUME IN THE STATE OF PARÁ, BRAZIL',
 '-OLD- THEORIES, -NEW- TECHNOLOGIES: UNDERSTANDING KNOWLEDGE SHARING AND LEARNING IN BRAZILIAN SOFTWARE DEVELOPMENT COMPANIES',
 '-P[E]NEU-, -AD[E]VOGADO- E -AF[E]TOSA-: O ABAIXAMENTO DAS VOGAIS SUARABÁTICAS NOS DADOS DO PROJETO ATLAS LINGUÍSTICO DO BRASIL',
 '-THE LAST TREE-, EXERCISING THE COMPUTATIONAL THINKING THROUGH A GRAPH GRAMMAR BASED EDUCATIONAL GAME',
 '-VANILLA- MALWARE: VANISHING ANTIVIRUSES BY INTERLEAVING LAYERS AND LAYERS OF ATTACKS',
 '. AN ONTOLOGY-BASED DIGITAL LIBRARY ON THE E-LEARNING DOMAIN.',
 '. CLIENT/SERVER AND MOBILE AGENT PARADIGMS - AN ANALYTICAL MODEL FOR PERFORMANCE EVALUATION',
 '. CLINMALDB: A CLINICAL FIELD-RESEARCH ORIENTED RELATIONAL DATABASE TO STUDY HUMAN MALARIA',
 '. ESCRITÓRIO DE PROJETOS: CARACTERÍSTICAS, VANTAGENS E O PLANEJAMENTO DE SUA IMPLANTAÇÃO NO SETOR PÚBLICO',
 '. ESTIMATION OF ENERGY CONSUMPTION AND EXECUTION TIME IN EARLY PHASES OF DESIGN LIFECYCLELIFECYCLE: AN APPLICATION TO BIOMEDICAL SYSTEMS',

In [10]:
map_production_to_id = {production: idx for idx, production in enumerate(unique_productions)}
map_production_to_id

{'                HALITE                DS</SUB>              </I>              : FAST AND SCALABLE SUBSPACE CLUSTERING FOR MULTIDIMENSIONAL DATA STREAMS': 0,
 '#CHI4BETTER4WHOM?': 1,
 '#DEOLHONOSCORAIS: A POLYGONAL ANNOTATED DATASET TO OPTIMIZE CORAL MONITORING': 2,
 '#FIQUEEMCASA, MAS SE MANTENHA ENSINANDO-APRENDENDO: ALGUMAS QUESTÕES EDUCACIONAIS EM TEMPOS DE PANDEMIA': 3,
 '#INOVAREAPRENDER: O USO DA ROBÓTICA EDUCACIONAL NO PROCESSO DE APRENDIZAGEM SIGNIFICATIVA ENVOLVENDO EDUCAÇÃO BÁSICA E ENSINO SUPERIOR': 4,
 '#PRACEGOVER: A LARGE DATASET FOR IMAGE CAPTIONING IN PORTUGUESE': 5,
 '#PRACEGOVER: INVESTIGATING THE DESCRIPTION OF VISUAL CONTENT IN BRAZILIAN ONLINE SOCIAL MEDIA': 6,
 '#RURALCONTRAAEDES: PLATAFORMA DE  MONITORAMENTO ONLINE DE FOCOS  DO MOSQUITO AEDES AEGYPIT  XXI ENAPET 2016: ENCONTRO NACIONAL DE GRUPOS PET': 7,
 '#RURALCONTRACORONA: UMA PLATAFORMA DE APOIO À DIFUSÃO DE AÇÕES CONTRA COVID-19 NO ÂMBITO DA BAIXADA FLUMINENSE': 8,
 '#STAYHOME: MONITORING SOCIAL DISTANCING TRENDS IN AMAZONAS DURING THE COVID-19 PANDEMIC USING GOOGLE MOBILE DATA': 9,
 '#TEAMINF AT SEMEVAL-2018 TASK 2: EMOJI PREDICTION IN TWEETS': 10,
 '#TWINTERA!: A SOCIAL MATCHING ENVIRONMENT BASED ON MICROBLOGGING': 11,
 '#WASHTHEHATE: UNDERSTANDING THE PREVALENCE OF ANTI-ASIAN PREJUDICE ON TWITTER DURING THE COVID-19 PANDEMIC': 12,
 '#WORLDCUP2014 ON TWITTER': 13,
 '$$S^2FS$$: SINGLE SCORE FEATURE SELECTION APPLIED TO THE PROBLEM OF DISTINGUISHING LONG NON-CODING RNAS FROM PROTEIN CODING TRANSCRIPTS': 14,
 '$${IN_K}$$ : A NON-FREGEAN LOGIC OF EXPLICIT KNOWLEDGE': 15,
 '$${LAMBDA }$$ &#955; -LGP: AN IMPROVED VERSION OF LINEAR GENETIC PROGRAMMING EVALUATED IN THE ANT TRAIL PROBLEM': 16,
 '$C^{\\AL}$-CLASSICAL SOLUTIONS FOR AN  ABSTRACT   NON-AUTONOMOUS   INTEGRO-DIFFERENTIAL EQUATIONS.': 17,
 '$DC_{F}$-INTEGRALS: GENERALIZING C$_{F}$-INTEGRALS BY MEANS OF RESTRICTED DISSIMILARITY FUNCTIONS': 18,
 '$IN_I$ : AN INTUITIONISTIC LOGIC WITHOUT FREGEAN AXIOM AND WITH PREDICATES FOR TRUTH AND FALSITY': 19,
 '$MATHCAL{IMA}$ - $MATHCAL{CID}$ : AN INTEGRATED MODELING APPROACH FOR DEVELOPING EDUCATIONAL MODULES': 20,
 '$O(N)$ TIME ALGORITHMS FOR DOMINATING INDUCED MATCHING PROBLEMS': 21,
 "&#22522;&#20110;&#22797;&#26434;&#32593;&#32476;&#30340;&#26426;&#22120;&#23398;&#20064;&#26041;&#27861; (CHINESE VERSION OF THE BOOK 'MACHINE LEARNING IN COMPLEX NETWORKS')": 22,
 '&#61623; ANÁLISE DE ROBUSTEZ DAS MARCAS D?ÁGUA NO DOMÍNIO ESPACIAL': 23,
 '&#61623; MARCA D?ÁGUA INSERÇÃO E ATAQUE': 24,
 '&#61713; USING INFORMATION TECHNOLOGY FOR PERSONALIZING THE COMPUTER SCIENCE TEACHING': 25,
 '&#65279;&#65279;&#65279;AGREGAÇÃO DE PACOTES EM AMBIENTES COM ENLACES DE BAIXA CAPACIDADE DE TRANSMISSÃO': 26,
 '&#8203; IMPLEMENTAÇÃO PARALELA DE ALGORITMOS DE CLASSIFICAÇÃO DE  DADOS PARA UMA DSL DE VISUALIZAÇÃO DE DADOS GEO\xadESPACIAIS': 27,
 '&#8203;BAYESIAN OPTIMIZATION FOR PATH PLANNING OF UAVS IN MONITORING APPLICATIONS': 28,
 '&#8206;ON GENERALIZED MIXTURE FUNCTIONS': 29,
 '&#8459;&#8734;-FILTERING DESIGN FOR DISCRETE-TIME MARKOV JUMP SYSTEMS WITH HIDDEN PARAMETERS': 30,
 '&#945; -LABELLINGS OF LOBSTERS WITH MAXIMUM DEGREE THREE': 31,
 '&#945;-DIPERFECT DIGRAPHS': 32,
 '&#945;-IDEALS OF FUZZY LATTICES': 33,
 '&#946;3-IRT: A NEW ITEM RESPONSE MODEL AND ITS APPLICATIONS': 34,
 '&#946;CAMKII REGULATES BIDIRECTIONAL LONG-TERM PLASTICITY IN CEREBELLAR PURKINJE CELLS BY A CAMKII/PP2B SWITCH MECHANISM': 35,
 '&#954;-ENTROPY BASED RESTRICTED BOLTZMANN MACHINES': 36,
 '&#956;SDN: AN SDN-BASED ROUTING ARCHITECTURE FOR WIRELESS SENSOR NETWORKS': 37,
 '&#956;TESLA PROTOCOL IN VEHICULAR NETWORKS': 38,
 '&#960;SOD-M: BUILDING SOC APPLICATIONS IN THE PRESENCE OF NON-FUNCTIONAL REQUIREMENTS': 39,
 '&#967;-DIPERFECT DIGRAPHS': 40,
 '&#969;-IVE METHODOLOGY: ADMISSIBLE INTERLEAVING ENTROPY METHODS APPLIED TO VIDEO STREAMING TRAFFIC CLASSIFICATION': 41,
 '&LT;TITLE&GT;A NEW METHOD TO EFFICIENTLY REDUCE HISTOGRAM DIMENSIONALITY&LT;/TITLE&GT;': 42,
 '&LT;TITLE&GT;A UNIFYING GRAPH-CUT IMAGE SEGMENTATION FRAMEWORK: ALGORITHMS IT ENCOMPASSES AND EQUIVALENCES AMONG THEM&LT;/TITLE&GT;': 43,
 '&LT;TITLE&GT;AUTOMATIC ANATOMY RECOGNITION VIA FUZZY OBJECT MODELS&LT;/TITLE&GT;': 44,
 '&LT;TITLE&GT;DEPOLARIZATION BEHAVIOR OF MULTIPLE SCATTERED LIGHT FROM AN OPTICALLY DENSE RANDOM MEDIUM&LT;/TITLE&GT;': 45,
 '&LT;TITLE&GT;NONLINEAR FEATURES EXTRACTION APPLIED TO POLLEN GRAIN IMAGES&LT;/TITLE&GT;': 46,
 '&LT;TITLE&GT;SIMULINK TOOLBOX FOR SIMULATION AND ANALYSIS OF OPTICAL FIBER LINKS&LT;/TITLE&GT;': 47,
 '&LT;TITLE&GT;TOWARD A PERCEPTION AND SENSOR FUSION ARCHITECTURE FOR A ROBOTIC AIRSHIP&LT;/TITLE&GT;': 48,
 '&QUOT; DADOS PRELIMINARES NO ESTUDO DA OSCILAÇÃO CORPORAL EM VOLUNTÁRIOS HÍGIDOS&QUOT;': 49,
 '&QUOT;APERTA O PLAY!&QUOT; ANÁLISE DA INTERAÇÃO EXPLORATÓRIA EM UM JOGO BASEADO EM PENSAMENTO COMPUTACIONAL': 50,
 '&QUOT;CLINICAL DEMENTIA RATING SCORE PREDICTION BASED ON AUTOMATED BRAIN IMAGE SEGMENTATION': 51,
 '&QUOT;EFFICIENT ALGORITHMS FOR THE HOTLINK ASSIGNMENT PROBLEM: THE WORST CASE SEARCH&QUOT;': 52,
 '&QUOT;EXTRAÇÃO E ANÁLISE DE CARACTERÍSTICAS EM TERMOGRAMAS PARA AUXÍLIO AO DIAGNÓSTICO DE CÂNCER DE MAMA': 53,
 '&QUOT;FUI CONTRATADO PARA ENSINAR COMPUTAÇÃO!&QUOT;: UM OLHAR SOBRE A SUPOSTA NEUTRALIDADE POLÍTICO-PEDAGÓGICA DO PROFESSOR UNIVERSITÁRIO DE COMPUTAÇÃO NO BRASIL': 54,
 '&QUOT;GREEDY APPROACH FOR IMAGE RESTORATION BASED ON ENERGY MINIMIZATION&QUOT;': 55,
 '&QUOT;IS ANYBODY THERE?&QUOT;': 56,
 '&QUOT;KEEP IT SIMPLE, LAZY&QUOT; -- METALAZY: A NEW METASTRATEGY FOR LAZY TEXT CLASSIFICATION': 57,
 '&QUOT;PERFORMANCE EVALUATION OF DISTRIBUTION IN OODBMS: A CASE STUDY WITH O2&QUOT;': 58,
 '&QUOT;POLUIÇÃO EM REDES SOCIAIS DE DISTRIBUIÇÃO DE VIDEOS': 59,
 '&QUOT;THE MAGIC OF SCIENCE:&QUOT; BEYOND ACTION, A CASE STUDY ON LEARNING THROUGH SOCIOENACTION': 60,
 '&QUOT;THIS CONVERSATION WILL BE RECORDED&QUOT;: AUTOMATICALLY GENERATING INTERACTIVE DOCUMENTS FROM CAPTURED MEDIA': 61,
 '&QUOT;TODAY IS SO COOL NOBODY WANTS TO LEAVE&QUOT;: WHAT MAKES TEENAGERS ENGAGED IN DEVELOPING EDUCATIONAL GAMES AT SCHOOL?': 62,
 '&QUOT;TWO-STAGE BINARY IMAGE OPERATOR DESIGN: AN APPROACH BASED ON INTERACTION INFORMATION&QUOT;': 63,
 '&QUOT;UM FRAMEWORK PARA O DESENVOLVIMENTO DE AGENTES COGNITIVOS EM JOGOS DE PRIMEIRA PESSOA.&QUOT;': 64,
 '&QUOT;UMA ABORDAGEM HÍBRIDA, BASEADA EM METAHEURÍSTICAS E NA HEURÍSTICA GENIUS, APLICADA AO PROBLEMA DE ROTEAMENTO DE VEÍCULOS COM COLETA E ENTREGA SIMULTÂNEA&QUOT;': 65,
 '&QUOT;UMA HEURISTICA EFICIENTE PARA PROBLEMAS DE ROTEAMENTO DE VEÍCULOS&QUOT;': 66,
 '&QUOT;UN OUTIL GÉNÉRIQUE DE GESTION PAR POLITIQUES: VALIDATION DE L?IMPLÉMENTATION DANS UN RÉSEAU SANS FILS WLAN': 67,
 '&QUOT;WEEPING ANGEL&QUOT;: BIBLIOTECA CROSS PLATAFORM DE BAIXO CUSTO PARA DETECÇÃO DE ATENÇÃO EM DISPOSITIVOS MÓVEIS': 68,
 '&QUOT;WHIZKEY: A WIZARD-BASED TOOL FOR INSTALLING DIGITAL LIBRARIES': 69,
 "'$\\ALPHA$-DIPERFECT DIGRAPHS'": 70,
 "''AEDES VS. REPELLENTS'': APPLYING TOWER DEFENSE DYNAMICS IN A DIGITAL GAME TO COMBAT THE MOSQUITO": 71,
 "''DESATENTOS'': UMA PROPOSTA DE JOGO DIGITAL PARA CONSCIENTIZAÇÃO DE SINTOMAS PRESENTES EM PORTADORES DO TDAH": 72,
 "'A COMPARISON OF DEEP LEARNING-BASED VISUAL ODOMETRY ALGORITHMS IN CHALLENGING SCENARIOS": 73,
 "'A MULTI-AGENT CYCLIC PATROLLING OF NODES STRATEGY ON DYNAMIC EDGE WEIGHTS GRAPHS'": 74,
 "'A MULTI-AGENT EDGE PATROLLING ON DYNAMIC EDGE WEIGHTS EULERIAN GRAPHS'": 75,
 "'A NOVA ELETRICIDADE': APLICAÇÕES, CHOQUES E TENDÊNCIAS DA IA MODERNA": 76,
 "'A ÚLTIMA ÁRVORE' DIGITAL: A IMPLEMENTAÇÃO DE UM JOGO EDUCACIONAL QUE UTILIZA MÉTODOS FORMAIS PARA ESTIMULAR O PENSAMENTO COMPUTACIONAL": 77,
 "'A ÚLTIMA ÁRVORE: A CHEGADA DA FAZENDA?, APLICANDO GRAMÁTICA DE GRAFOS COM ATRIBUTOS AO DESENVOLVIMENTO DO PENSAMENTO COMPUTACIONAL": 78,
 "'A ÚLTIMA ÁRVORE: O POVO DA CIDADE', UTILIZANDO A CONDIÇÃO NEGATIVA DE APLICAÇÃO EM UM JOGO EDUCACIONAL": 79,
 "'ALIGNING BUSINESS REQUIREMENTS WITH SERVICES  QUALITY CHARACTERISTICS BY USING LOGICAL ARCHITECTURES.'": 80,
 "'ALL THE THINGS THAT COME AND GO, STOP AND SAY HELLO': TOWARDS AN ONTOLOGICAL ACCOUNT OF HOW PARTICIPANTS ENTER AND EXIT EVENTS": 81,
 "'AN APPROACH FOR LEARNING AND CONSTRUCTION OF EXPRESSIVE ONTOLOGY FROM TEXT IN NATURAL LANGUAGE'": 82,
 "'AN ONTOLOGY ANALYSIS IMPLEMENTATION IN CONSTRAINT LOGIC PROGRAMMING'": 83,
 "'BATALHA DA VIZINHANÇA'': UM JOGO DE TABULEIRO PARA O COMBATE A DENGUE": 84,
 "'BDD ASSEMBLE!': A PAPER-BASED GAME PROPOSAL FOR BEHAVIOR DRIVEN DEVELOPMENT DESIGN LEARNING": 85,
 "'BN ANATOMY' AN INTERACTIVE AUGMENTED REALITY SYSTEM FOR LEARNING BONE ANATOMY": 86,
 "'C. B. (2021, OCTOBER). APRENDIZAGEM BASEADA EM JOGOS PARA CELULAR COM O APLICATIVO OPI: LIÇÕES APRENDIDAS COM UMA AVALIAÇÃO DE USABILIDADE PARA CRIANÇAS": 87,
 "'DEDUPLICATING LARGE VOLUMES OF DATA FROM NATURAL AND LEGAL ENTITIES IN THE GOVERNMENTAL FIELD": 88,
 "'DISPOSITIVO PARA COLETA E PROCESSAMENTO DE SINAIS CEREBRAIS E SUA INTEGRAÇÃO A CADEIRA DE RODAS": 89,
 "'EU TAMBÉM QUERO JOGAR!' - REAVALIANDO AS PRÁTICAS E DIRETRIZES DE ACESSIBILIDADE EM JOGOS": 90,
 "'EVERY MOVE YOU MAKE IN EVERY GAME YOU PLAY': CAN GAME LOGS DETERMINE PLAYER'S ENGAGEMENT?": 91,
 "'EVERYTHING I DISAGREE WITH IS #FAKENEWS': CORRELATING POLITICAL POLARIZATION AND SPREAD OF MISINFORMATION": 92,
 "'EXPLORING A THREE-DIMENSIONAL, REQUIREMENTS- BASED, BALANCED SCORECARD BUSINESS MODEL.'": 93,
 "'FLASH DETECTION': WHAT CAN YOU SEE IN RAPIDLY DISPLAYED IMAGES?": 94,
 "'FUZZY LOGIC SYSTEM MODELING ASIAN SOYBEAN RUST MONOCYCLIC PROCESS'": 95,
 "'GLOBAL MULTIPLE ALIGNMENT BASED ON PROFILE AND AGGLOMERATIVE SINGLE-LINK CLUSTERING: A COMPARATIVE STUDY WITH CLUSTAL-W (EMBL-EBI) TOOL'": 96,
 "'HYDRONODE: A LOW COST, ENERGY EFFICIENT, MULTI PURPOSE NODE FOR UNDERWATER SENSOR NETWORKS'": 97,
 "'IMPLEMENTING COFFEE RUST NEURO-FUZZY MODEL THROUGH GEOSCIENCE'": 98,
 "'IMPLEMENTING SOYBEAN RUST FUZZY LOGIC SYSTEM MODEL THROUGH GEOSCIENCE'": 99,
 "'IS LEARNING TO RANK WORTH IT?  A STATISTICAL ANALYSIS OF LEARNING TO RANK METHODS": 100,
 "'JOVENS PROGRAMADORES' NA PANDEMIA": 101,
 "'JOVENS PROGRAMADORES' NA PANDEMIA: ENSINO DE PROGRAMAÇÃO DE COMPUTADORES DE FORMA REMOTA": 102,
 "'JUNTOS VENCEREMOS' ? UM EXERGAME PARA TESTE DE JOGO MULTIPLAYER UTILIZANDO VISÃO COMPUTACIONAL": 103,
 "'JUNTOS VENCEREMOS' UM EXERGAME PARA TESTE DE JOGO MULTIPLAYER UTILIZANDO VISÃO COMPUTACIONAL": 104,
 "'KEEP IT SIMPLE, LAZY' -- METALAZY: A NEW METASTRATEGY FOR LAZY TEXT CLASSIFICATION": 105,
 "'LOOKS GOOD TO ME ;-)': ASSESSING SENTIMENT ANALYSIS TOOLS FOR PULL REQUEST DISCUSSIONS": 106,
 "'MERGE SOURCE CODING'": 107,
 "'MODELING AND SCHEDULING HARD REAL-TIME BIOMEDICAL SYSTEMS WITH TIMING AND ENERGY CONSTRAINTS - QUALIS: A. CIRCULAÇÃO: INTERNACIONAL.": 108,
 "'MORO NUM PAÍS TROPICAL': A CRISE POLÍTICA BRASILEIRA E HUMOR NO TWITTER": 109,
 "'MY LIFE DOESN'T HAVE TO BE AN OPEN BOOK': A MODEL TO HELP DESIGNERS TO ENHANCE PRIVACY CONTROLS ON SOCIAL NETWORK SITES": 110,
 "'NEURO-FUZZY MODELING COFFEE RUST MONOCYCLIC PROCESS'": 111,
 "'NO CODE ANOMALY IS AN ISLAND' -- ANOMALY AGGLOMERATION AS SIGN OF PRODUCT LINE INSTABILITIES": 112,
 "'NÃO QUEIMA MEU LED!' - UM JOGO DE REALIDADE VIRTUAL PARA O ENSINO DE CIRCUITOS DIGITAIS": 113,
 "'O COMPUTADOR COMO INSTRUMENTO AUXILIAR DE ENSINO.": 114,
 "'O USO DO CLASSROOM COMO RECURSO EDUCACIONAL NA EDUCAÇÃO DE JOVENS E ADULTOS": 115,
 "'P-MEDIAN AND P-CENTER APPLIED TO COLOR QUANTIZATION AND PIXEL MAPPING'": 116,
 "'PROCESSO DE PLANEJAMENTO PARA PRODUÇÃO, EXECUÇÃO E AVALIAÇÃO DE CONTEÚDOS CROSSMIDIÁTICOS, EDUCATIVOS E TELEVISIVOS": 117,
 "'RADIATION-INDUCED ERROR CRITICALITY IN MODERN HPC PARALLEL ACCELERATORS": 118,
 "'SISTEMA DE RECONHECIMENTO FACIAL PARA CONTROLO AUTOMÁTICO DE PRESENÇA EM SALA DE AULAS'": 119,
 "'SIX-WRITINGS' MULTIMODAL PROCESSING WITH PICTOPHONETIC CODING TO ENHANCE CHINESE LANGUAGE MODELS": 120,
 "'STRESS LEVEL OF CRITICAL CARE NURSES: EVALUATION BY HEART RATE VARIABILITY'": 121,
 "'TÉCNICAS DE APRENDIZADO PROFUNDO PARA AUXÍLIO NA DETECÇÃO DO COVID-19 EM IMAGENS DE RAIOS-X DO TÓRAX'": 122,
 "'UAI! QUE ISSO SÔ!': CONHECENDO O 'MINEIRÊS' ATRAVÉS DE UM JOGO DIGITAL": 123,
 "'ULTIMATE FOOD DEFENSE': A SERIOUS GAME FOR HEALTHY EATING BEHAVIOR AWARENESS": 124,
 "'UMA HEURÍSTICA BASEADA NO MÉTODO DE BUSCA A* APLICADA AO PROBLEMA DE ROTEAMENTO'": 125,
 "'UNIVERSITY UNIVERSE': A MOBILE GAME TO SIMULATE THE UNIVERSITY STUDENT LIFE": 126,
 "'VALUES AT PLAY - BRASIL' AVALIAÇÃO DE ARTEFATO": 127,
 "'VIDA DE ES': PROTÓTIPO DE UM JOGO DE CARTAS PARA O ENSINO DE SITUAÇÕES PRÁTICAS VIVENCIADAS POR UM ENGENHEIRO DE SOFTWARE": 128,
 "'VIDEO POLLUTION ON THE WEB''": 129,
 "'YOU?RE ON A BICYCLE WITH A LITTLE MOTOR': BENEFITS AND CHALLENGES OF USING AI CODE ASSISTANTS": 130,
 "'É PRA FAZER O QUE, PROFESSORA?' FOMENTANDO INICIATIVA E INOVAÇÃO NA DISCIPLINA DE IHM": 131,
 '(2A ED.) O BEIJO DE JULIANA: QUATRO FÍSICOS TEÓRICOS CONVERSAM SOBRE CRIANÇAS, CIÊNCIAS DA COMPLEXIDADE, BIOLOGIA, POLÍTICA, RELIGIÃO E FUTEBOL...': 132,
 '(3,4,6)-FULLERENES GRAPHS': 133,
 '(ARTIGO CONVIDADO PELA COMISSAO ORGANIZADORA)TUTOR BEHAVIOUR IN A MULTI-AGENT ITS GUIDED THROUGH MENTAL STATES ACTIVITIES': 134,
 '(ARTIGO SOBRE A DISSERTAÇÃO:) SISTEMA BIOMÉDICO PARA AVALIAÇÃO E REABILITAÇÃO MOTORA EM HEMIPARÉTICOS POR AVC': 135,
 '(AUTO) SINTONIA-FINA EM SISTEMAS DE BANCOS DE DADOS NAS ORGANIZAÇÕES': 136,
 '(BEST PAPER) REDES AUTO-RECONFIGURÁVEIS RANDOMIZADAS PARA COMUNICAÇÃO DISTRIBUÍDA EM DATACENTERS': 137,
 '(BR-SCMM) BRAZILIAN SMART CITY MATURITY MODEL: A PERSPECTIVE FROM THE HEALTH DOMAIN': 138,
 '(CAUSAL/INTERPRETATIVE UNDERSTANDING), (LAW-GOVERNED DESCRIPTION/PREDICTION), AND EMPIRICAL LEGAL STUDIES: COMMENT': 139,
 '(CHAR)LAR: UMA EXPERIMENTAC&#807;A&#771;O DE GERAC&#807;A&#771;O DE POEMAS BASEADA EM REDES NEURAIS RECORRENTES': 140,
 '(CHAR)LAR: UMA EXPERIMENTAÇÃO DE GERAÇÃO DE POEMAS BASEADA EM REDES NEURAIS RECORRENTES': 141,
 '(CIA)&LT;SUP&GT;2&LT;/SUP&GT;-ITS: INTERCONNECTING MOBILE AND UBIQUITOUS DEVICES FOR INTELLIGENT TRANSPORTATION SYSTEMS': 142,
 '(CIA)2-ITS: INTERCONNECTING MOBILE AND UBIQUITOUS DEVICES FOR INTELLIGENT TRANSPORTATION SYSTEMS': 143,
 '(CIA)2</SUP>-ITS: INTERCONNECTING MOBILE AND UBIQUITOUS DEVICES FOR INTELLIGENT TRANSPORTATION SYSTEMS': 144,
 '(DE) CONSTRUCTING BIAS ON SKIN LESION DATASETS': 145,
 '(DEEP) LEARNING FROM FRAMES': 146,
 '(DOI 10.5753/CBIE.SBIE.2007.155-158) CARACTERIZAÇÃO DAS ÊNFASES DE EDUCAÇÃO E TREINAMENTO EM AMBIENTES VIRTUAIS 3D': 147,
 '(DOI: 10.1007/978-3-319-31307-8_8) SERIOUS GAMES FOR BALANCE IMPROVEMENT: A SYSTEMATIC LITERATURE MAPPING': 148,
 '(DOI:10.1007/978-3-319-31307-8_25) DIGITAL GAMES FOR MATH LITERACY: A SYSTEMATIC LITERATURE MAPPING ON BRAZILIAN PUBLICATIONS': 149,
 "(ETNO) INFORMÁTICA NA EDUCAÇÃO: USO N'SAMAT COMO ORGANIZADOR PRÉVIO PARA AUXILIAR NA APRENDIZAGEM DE ARITMÉTICA EM TRÊS ESCOLAS MOÇAMBICANAS.": 150,
 '(IN)SEGURANÇA DO VOTO ELETRÔNICO NO BRASIL': 151,
 '(INTER)DISCIPLINARIDADE E TRANSVERSALIDADES: O PROJETO DE FORMAÇÃO SUPERIOR DA UNIVERSIDADE FEDERAL DO ABC': 152,
 '(K, L)-SANDWICH PROBLEM: WHY NOT ASK FOR SPECIAL KINDS OF BREAD?': 153,
 '(K,L)-P_4-SPARSE GRAPHS (POSTER)': 154,
 '(K,L)-SANDWICH PROBLEM: WHY NOT ASK FOR SPECIAL KINDS OF BREAD?': 155,
 '(K,L)-SANDWICH PROBLEMS: WHY NOT ASK FOR SPECIAL KINDS OF BREAD?': 156,
 '(K,L)-SANDWICH PROBLEMS: WHY NOT ASK FOR SPECIAL KINDS OF BREAD?.': 157,
 '(L,U)-BOUNDED PRIORITY QUEUES': 158,
 '(M,K)-GUR GAME: EXPLOITING MESSAGE DISCARDS IN ORDER TO INCREASE THE LIFETIME AND SPATIAL DIVERSITY IN AUTONOMIC WIRELESS SENSOR NETWORKS': 159,
 '(META)MODELAGEM DE ESPAÇOS INTELIGENTES PESSOAIS E ESPAÇOS INTELIGENTES FIXOS PARA APLICAÇÕES UBÍQUAS': 160,
 '(MICRO)CELL COVERAGE AREA USING STATISTICAL METHODS': 161,
 '(MINISYMPOSIUM INVITED TALK) BLOCK COORDINATE DESCENT FOR SMOOTH NONCONVEX CONSTRAINED MINIMIZATION': 162,
 '(MINISYMPOSIUM INVITED TALK) ERNESTO BLOCK COORDINATE DESCENT AND THE CLOSE ENOUGH TRAVELING SALESMAN PROBLEM': 163,
 '(MIS)INFORMATION DISSEMINATION IN WHATSAPP: GATHERING, ANALYZING AND COUNTERMEASURES': 164,
 '(NO PRELO DA EDITORA)PROPRIEDADE INTELECTUAL, EMPREENDEDORISMO E BUSCA DE INFORMAÇÃO TECNOLÓGICA PARA A INFORMÁTICA NA EDUCAÇÃO': 165,
 '(NON-) HOMOMORPHIC APPROACHES TO DENOISE INTENSITY SAR IMAGES WITH NON-LOCAL MEANS AND STOCHASTIC DISTANCES': 166,
 '(N¿, T, N)-IMPLICATIONS': 167,
 '(ORCHIDEA) UMA PRIMEIRA APLICAÇÃO PARA PRÁTICAS MUSICAIS COLETIVAS NA ORQUESTRA DE IDEIAS': 168,
 '(PLENARY TALK) AUGMENTED LAGRANGIAN METHODS: COMPLEXITY AND PERFORMANCE': 169,
 '(PLENARY TALK) COMPLEXITY RESULTS IN NONLINEAR OPTIMIZATION': 170,
 '(PLENARY TALK) CURRENT WORK IN THE DEVELOPMENT OF AUGMENTED LAGRANGIAN SOFTWARE': 171,
 '(PLENARY TALK) PRACTICAL AUGMENTED LAGRANGIAN METHODS': 172,
 '(PLENARY TALK) SAFEGUARDED AUGMENTED LAGRANGIAN METHODS FOR NONCONVEX OPTIMIZATION: CONVERGENCE, COMPLEXITY AND EXPERIMENTS': 173,
 '(RE) CONHECENDO A UNIVERSIDADE DE SÃO PAULO - CONTRIBUIÇÕES DO ENSINO, DA PESQUISA E DA EXTENSÃO NO CAMPO DAS DEFICIÊNCIAS': 174,
 '(RE) CONHECENDO A USP: CONTRIBUIÇÕES DO ENSINO, DA PESQUISA E DA EXTENSÃO NO CAMPO DAS DEFICIÊNCIAS': 175,
 '(RE)ACTIVE LOAD CONTROL BASED ON RADIO LINK QUALITY FOR THE UMTS/WCDMA FORWARD LINK': 176,
 '(RE)CONFIGURATION ALGORITHMS FOR PEER-TO-PEER OVER AD HOC NETWORKS': 177,
 '(RE)CONHECENDO A USP - CONTRIBUIÇÕES DA PESQUISA E DA EXTENSÃO NO CAMPO DAS DEFICIÊNCIAS: CURSOS PRESENTES': 178,
 '(RE)EVALUATING THE INFLUENCE OF CONTEXTUALIZED EXAMPLES IN TEACHING AN INTRODUCTORY SOFTWARE ENGINEERING COURSE IN BRAZIL': 179,
 '(RE-) CONFIGURABLE REAL-TIME OPERATING SYSTEMS AND THEIR APPLICATIONS': 180,
 '(REQUIREMENT) EVOLUTION REQUIREMENTS FOR ADAPTIVE SYSTEMS': 181,
 '(RESUMO) EXPRESSIVENESS AND DEFINABILITY IN CIRCUNSCRIPTION': 182,
 '(RESUMO) SCHEMATIC RULES IN NATURAL DEDUCTION FOR LOGIC WITH MODAL OPERATORS': 183,
 '(S,N)-IMPLICATIONS ON BOUNDED LATTICES': 184,
 '(STAR, K)-COLOURINGS OF GRAPHS WITH BOUNDED TREEWIDTH': 185,
 '(T, N)-IMPLICATIONS': 186,
 '(T, N)-IMPLICATIONS AND SOME FUNCTIONAL EQUATIONS': 187,
 '(TEAM DESCRIPTION PAPER) SISTEMA DA ESQUIPE DE FUTEBOL DE ROBÔS ARARABOTS AZUL': 188,
 '(WIP) TASKS SELECTION POLICIES FOR SECURING SENSITIVE DATA ON WORKFLOW SCHEDULING IN CLOUDS': 189,
 '(XOR) XBRL-OBJETO-RELACIONAL: UM FRAMEWORK PARA EXTRAÇÃO, TRANSFORMAÇÃO, CARGA E AUDITORIA DE DADOS FINANCEIROS EM BASES RELACIONAIS E INSTÂNCIAS XBRL': 190,
 ', A SCORING TOOL FOR BOUNDARY DETERMINATION BETWEEN REPETITIVE AND NON-REPETITIVE PROTEIN SEQUENCES': 191,
 ', DESENVOLVIMENTO DE UM SISTEMA GRÁFICO INTERATIVO PARA MODELAGEM E ANIMAÇÃO FACIAL': 192,
 '- 2 -NORM FEATURE LEAST MEAN SQUARE ALGORITHM': 193,
 '- O USO DE PROJETOS-PILOTO. CARACTERIZAÇÃO DO ESTADO DA PRÁTICA DAS ATIVIDADES DE TESTE EM UM CENÁRIO DE DESENVOLVIMENTO DE SOFTWARE BRASILEIRO': 194,
 '- TRANSMISSION POWER CONTROL IN MAC PROTOCOLS FOR WIRELESS SENSOR NETWORKS': 195,
 '--HOMOGENEOUS FUNCTIONS AND A GENERALIZATION OF DIRECTIONAL MONOTONICITY': 196,
 '-ASYMPTOTICALLY PERIODIC SOLUTIONS FOR ABSTRACT EQUATIONS WITH STATE-DEPENDENT DELAY': 197,
 '-BRAZILIAN STYLE SCIENCE--AN ANALYSIS OF THE DIFFERENCE BETWEEN BRAZILIAN AND INTERNATIONAL COMPUTER SCIENCE DEPARTMENTS AND GRADUATE PROGRAMS USING SOCIAL NETWORKS ANALYSIS AND BIBLIOMETRICS': 198,
 '-COLORING OF TIGHT GRAPHS': 199,
 '-CONVEXITY ON GRAPHS WITH DIAMETER TWO: COMPUTING HULL AND INTERVAL NUMBERS': 200,
 '-EU FIZ MEU GAME-: UM FRAMEWORK PARA DESENVOLVIMENTO DE JOGOS POR CRIANÇAS': 201,
 '-FILTERING FOR MARKOV JUMP LINEAR SYSTEMS WITH PARTIAL INFORMATION ON THE JUMP PARAMETER': 202,
 '-FIXING THE CURSE OF THE BAD PRODUCT DESCRIPTIONS- - SEARCH-BOOSTED TAG RECOMMENDATION FOR E-COMMERCE PRODUCTS': 203,
 '-FREE- AS IN FREEDOM TO PROTEST?': 204,
 '-GROUPING FUNCTIONS: A GENERALIZATION OF BIVARIATE GROUPING FUNCTIONS BY                            -CONORMS': 205,
 '-NEAREST NEIGHBOR REGRESSION IN THE ESTIMATION OF TRUNK VOLUME IN THE STATE OF PARÁ, BRAZIL': 206,
 '-OLD- THEORIES, -NEW- TECHNOLOGIES: UNDERSTANDING KNOWLEDGE SHARING AND LEARNING IN BRAZILIAN SOFTWARE DEVELOPMENT COMPANIES': 207,

In [18]:
len(map_production_to_id)

165270

In [11]:
df_productions["production_id"] = df_productions["production"].map(map_production_to_id)
df_productions

,name,citation,lattes_id,institution,production,authors,location,type,year,issn,production_id
0,Jose Maria Nazar David,"[Jose Maria Nazar David, DAVID, JOSE MARIA, DA...",3640497501056163,UFJF,DESIGNING COLLABORATION THROUGH A WEB-BASED GR...,"[Jose Maria Nazar David, Marcos R. S. Borges]",International Journal of Computer Applications...,PERIODICO,2004,09528091,55758
1,Jose Maria Nazar David,"[Jose Maria Nazar David, DAVID, JOSE MARIA, DA...",3640497501056163,UFJF,SUPPORTING AWARENESS IN GROUPWARE THROUGH AN A...,"[Rita Suzana Pitangueira Maciel, Jose Maria Na...",JOURNAL OF UNIVERSAL COMPUTER SCIENCE,PERIODICO,2009,0948695X,139151
2,Jose Maria Nazar David,"[Jose Maria Nazar David, DAVID, JOSE MARIA, DA...",3640497501056163,UFJF,MANAGEMENT OF SCIENTIFIC EXPERIMENTS IN COMPUT...,"[Regina Maria Maciel Braga, Fernanda Cláudia A...",iSys - Revista Brasileira de Sistemas de Infor...,PERIODICO,2012,19842902,94332
3,Jose Maria Nazar David,"[Jose Maria Nazar David, DAVID, JOSE MARIA, DA...",3640497501056163,UFJF,SCIENTIFIC PROVENANCE METADATA CAPTURE AND MAN...,"[Wander Gaspar, Regina Maria Maciel Braga, Fer...","International Journal of Metadata, Semantics a...",PERIODICO,2015,17442621,129626
4,Jose Maria Nazar David,"[Jose Maria Nazar David, DAVID, JOSE MARIA, DA...",3640497501056163,UFJF,PERSONNA: PROPOSTA DE ONTOLOGIA DE CONTEXTO E ...,"[Paulo Rezende, Crystiam Kelle Pereira, Fernan...",Revista Brasileira de Informática na Educação,PERIODICO,2015,14145685,114872
...,...,...,...,...,...,...,...,...,...,...,...
230926,Leandro Santiago de Araujo,"[Leandro Santiago de Araujo, L. S. ARAUJO, LEA...",6358983442870515,UFF,PRUNING WEIGHTLESS NEURAL NETWORKS,"[Zachary Susskind, Igor Dantas Dos Santos Mira...",30th European Symposium on Artificial Neural N...,CONFERENCIA,2022,None,121785
230927,Leandro Santiago de Araujo,"[Leandro Santiago de Araujo, L. S. ARAUJO, LEA...",6358983442870515,UFF,GSINK - A RUNTIME FOR GAMMA PROGRAMS AND ITS C...,"[MELLO, RUI R., PAILLARD, GABRIEL A. L., Leand...",2023 IEEE International Parallel and Distribut...,CONFERENCIA,2023,None,78378
230928,Leandro Santiago de Araujo,"[Leandro Santiago de Araujo, L. S. ARAUJO, LEA...",6358983442870515,UFF,HEURISTICS FOR T-ADMISSIBILITY WITH COMPLEX NE...,"[Carlos Thadeu Duarte Santos, Anderson Zudio, ...",SBPO 2023: Simpósio Brasileiro de Pesquisa Ope...,CONFERENCIA,2023,None,79403
230929,Leandro Santiago de Araujo,"[Leandro Santiago de Araujo, L. S. ARAUJO, LEA...",6358983442870515,UFF,GERANDO BASE DE GRAFOS NÃO ISOMORFOS COM SEUS ...,"[Felipe Souza, Leandro Santiago de Araujo, Luí...",SBPO 2023: Simpósio Brasileiro de Pesquisa Ope...,CONFERENCIA,2023,None,76459
230930,Leandro Santiago de Araujo,"[Leandro Santiago de Araujo, L. S. ARAUJO, LEA...",6358983442870515,UFF,PARALELISMO E HEURÍSTICAS PARA O PROBLEMA DA M...,"[Thiago Lopes Nascimento, Fábio Protti, Luís F...",SBPO 2023: Simpósio Brasileiro de Pesquisa Ope...,CONFERENCIA,2023,None,112702

## 2.2. Productions with no authors

In [13]:
df_productions = preprocesser.drop_authorless_productions(df_productions)
df_productions

,name,citation,lattes_id,institution,production,authors,location,type,year,issn,production_id
0,Jose Maria Nazar David,"[Jose Maria Nazar David, DAVID, JOSE MARIA, DA...",3640497501056163,UFJF,DESIGNING COLLABORATION THROUGH A WEB-BASED GR...,"[Jose Maria Nazar David, Marcos R. S. Borges]",International Journal of Computer Applications...,PERIODICO,2004,09528091,55758
1,Jose Maria Nazar David,"[Jose Maria Nazar David, DAVID, JOSE MARIA, DA...",3640497501056163,UFJF,SUPPORTING AWARENESS IN GROUPWARE THROUGH AN A...,"[Rita Suzana Pitangueira Maciel, Jose Maria Na...",JOURNAL OF UNIVERSAL COMPUTER SCIENCE,PERIODICO,2009,0948695X,139151
2,Jose Maria Nazar David,"[Jose Maria Nazar David, DAVID, JOSE MARIA, DA...",3640497501056163,UFJF,MANAGEMENT OF SCIENTIFIC EXPERIMENTS IN COMPUT...,"[Regina Maria Maciel Braga, Fernanda Cláudia A...",iSys - Revista Brasileira de Sistemas de Infor...,PERIODICO,2012,19842902,94332
3,Jose Maria Nazar David,"[Jose Maria Nazar David, DAVID, JOSE MARIA, DA...",3640497501056163,UFJF,SCIENTIFIC PROVENANCE METADATA CAPTURE AND MAN...,"[Wander Gaspar, Regina Maria Maciel Braga, Fer...","International Journal of Metadata, Semantics a...",PERIODICO,2015,17442621,129626
4,Jose Maria Nazar David,"[Jose Maria Nazar David, DAVID, JOSE MARIA, DA...",3640497501056163,UFJF,PERSONNA: PROPOSTA DE ONTOLOGIA DE CONTEXTO E ...,"[Paulo Rezende, Crystiam Kelle Pereira, Fernan...",Revista Brasileira de Informática na Educação,PERIODICO,2015,14145685,114872
...,...,...,...,...,...,...,...,...,...,...,...
230912,Leandro Santiago de Araujo,"[Leandro Santiago de Araujo, L. S. ARAUJO, LEA...",6358983442870515,UFF,PRUNING WEIGHTLESS NEURAL NETWORKS,"[Zachary Susskind, Igor Dantas Dos Santos Mira...",30th European Symposium on Artificial Neural N...,CONFERENCIA,2022,None,121785
230913,Leandro Santiago de Araujo,"[Leandro Santiago de Araujo, L. S. ARAUJO, LEA...",6358983442870515,UFF,GSINK - A RUNTIME FOR GAMMA PROGRAMS AND ITS C...,"[MELLO, RUI R., PAILLARD, GABRIEL A. L., Leand...",2023 IEEE International Parallel and Distribut...,CONFERENCIA,2023,None,78378
230914,Leandro Santiago de Araujo,"[Leandro Santiago de Araujo, L. S. ARAUJO, LEA...",6358983442870515,UFF,HEURISTICS FOR T-ADMISSIBILITY WITH COMPLEX NE...,"[Carlos Thadeu Duarte Santos, Anderson Zudio, ...",SBPO 2023: Simpósio Brasileiro de Pesquisa Ope...,CONFERENCIA,2023,None,79403
230915,Leandro Santiago de Araujo,"[Leandro Santiago de Araujo, L. S. ARAUJO, LEA...",6358983442870515,UFF,GERANDO BASE DE GRAFOS NÃO ISOMORFOS COM SEUS ...,"[Felipe Souza, Leandro Santiago de Araujo, Luí...",SBPO 2023: Simpósio Brasileiro de Pesquisa Ope...,CONFERENCIA,2023,None,76459
230916,Leandro Santiago de Araujo,"[Leandro Santiago de Araujo, L. S. ARAUJO, LEA...",6358983442870515,UFF,PARALELISMO E HEURÍSTICAS PARA O PROBLEMA DA M...,"[Thiago Lopes Nascimento, Fábio Protti, Luís F...",SBPO 2023: Simpósio Brasileiro de Pesquisa Ope...,CONFERENCIA,2023,None,112702

## 2.3. Citation normalization

In [14]:
df_productions = preprocesser.normalize_authors(df_productions)
df_productions

,name,citation,lattes_id,institution,production,authors,location,type,year,issn,production_id
0,Jose Maria Nazar David,"[Jose Maria Nazar David, DAVID, JOSE MARIA, DA...",3640497501056163,UFJF,DESIGNING COLLABORATION THROUGH A WEB-BASED GR...,"[Jose Maria Nazar David, Marcos Roberto da Sil...",International Journal of Computer Applications...,PERIODICO,2004,09528091,55758
1,Jose Maria Nazar David,"[Jose Maria Nazar David, DAVID, JOSE MARIA, DA...",3640497501056163,UFJF,SUPPORTING AWARENESS IN GROUPWARE THROUGH AN A...,"[Rita Suzana Pitangueira Maciel, Jose Maria Na...",JOURNAL OF UNIVERSAL COMPUTER SCIENCE,PERIODICO,2009,0948695X,139151
2,Jose Maria Nazar David,"[Jose Maria Nazar David, DAVID, JOSE MARIA, DA...",3640497501056163,UFJF,MANAGEMENT OF SCIENTIFIC EXPERIMENTS IN COMPUT...,"[Regina Maria Maciel Braga, Fernanda Cláudia A...",iSys - Revista Brasileira de Sistemas de Infor...,PERIODICO,2012,19842902,94332
3,Jose Maria Nazar David,"[Jose Maria Nazar David, DAVID, JOSE MARIA, DA...",3640497501056163,UFJF,SCIENTIFIC PROVENANCE METADATA CAPTURE AND MAN...,"[Wander Gaspar, Regina Maria Maciel Braga, Fer...","International Journal of Metadata, Semantics a...",PERIODICO,2015,17442621,129626
4,Jose Maria Nazar David,"[Jose Maria Nazar David, DAVID, JOSE MARIA, DA...",3640497501056163,UFJF,PERSONNA: PROPOSTA DE ONTOLOGIA DE CONTEXTO E ...,"[Paulo Rezende, Crystiam Kelle Pereira, Fernan...",Revista Brasileira de Informática na Educação,PERIODICO,2015,14145685,114872
...,...,...,...,...,...,...,...,...,...,...,...
230912,Leandro Santiago de Araujo,"[Leandro Santiago de Araujo, L. S. ARAUJO, LEA...",6358983442870515,UFF,PRUNING WEIGHTLESS NEURAL NETWORKS,"[Zachary Susskind, Igor Dantas Dos Santos Mira...",30th European Symposium on Artificial Neural N...,CONFERENCIA,2022,None,121785
230913,Leandro Santiago de Araujo,"[Leandro Santiago de Araujo, L. S. ARAUJO, LEA...",6358983442870515,UFF,GSINK - A RUNTIME FOR GAMMA PROGRAMS AND ITS C...,"[MELLO, RUI R., Gabriel Antoine Louis Paillard...",2023 IEEE International Parallel and Distribut...,CONFERENCIA,2023,None,78378
230914,Leandro Santiago de Araujo,"[Leandro Santiago de Araujo, L. S. ARAUJO, LEA...",6358983442870515,UFF,HEURISTICS FOR T-ADMISSIBILITY WITH COMPLEX NE...,"[Carlos Thadeu Duarte Santos, Anderson Zudio, ...",SBPO 2023: Simpósio Brasileiro de Pesquisa Ope...,CONFERENCIA,2023,None,79403
230915,Leandro Santiago de Araujo,"[Leandro Santiago de Araujo, L. S. ARAUJO, LEA...",6358983442870515,UFF,GERANDO BASE DE GRAFOS NÃO ISOMORFOS COM SEUS ...,"[Felipe Souza, Leandro Santiago de Araujo, Luí...",SBPO 2023: Simpósio Brasileiro de Pesquisa Ope...,CONFERENCIA,2023,None,76459
230916,Leandro Santiago de Araujo,"[Leandro Santiago de Araujo, L. S. ARAUJO, LEA...",6358983442870515,UFF,PARALELISMO E HEURÍSTICAS PARA O PROBLEMA DA M...,"[Thiago Lopes Nascimento, Fábio Protti, Luís F...",SBPO 2023: Simpósio Brasileiro de Pesquisa Ope...,CONFERENCIA,2023,None,112702

In [15]:
df_productions = preprocesser.explode_authors(df_productions)
df_productions

,name,citation,lattes_id,institution,production,authors,location,type,year,issn,production_id
0,Jose Maria Nazar David,"[Jose Maria Nazar David, DAVID, JOSE MARIA, DA...",3640497501056163,UFJF,DESIGNING COLLABORATION THROUGH A WEB-BASED GR...,Jose Maria Nazar David,International Journal of Computer Applications...,PERIODICO,2004,09528091,55758
1,Jose Maria Nazar David,"[Jose Maria Nazar David, DAVID, JOSE MARIA, DA...",3640497501056163,UFJF,DESIGNING COLLABORATION THROUGH A WEB-BASED GR...,Marcos Roberto da Silva Borges,International Journal of Computer Applications...,PERIODICO,2004,09528091,55758
2,Jose Maria Nazar David,"[Jose Maria Nazar David, DAVID, JOSE MARIA, DA...",3640497501056163,UFJF,SUPPORTING AWARENESS IN GROUPWARE THROUGH AN A...,Rita Suzana Pitangueira Maciel,JOURNAL OF UNIVERSAL COMPUTER SCIENCE,PERIODICO,2009,0948695X,139151
3,Jose Maria Nazar David,"[Jose Maria Nazar David, DAVID, JOSE MARIA, DA...",3640497501056163,UFJF,SUPPORTING AWARENESS IN GROUPWARE THROUGH AN A...,Jose Maria Nazar David,JOURNAL OF UNIVERSAL COMPUTER SCIENCE,PERIODICO,2009,0948695X,139151
4,Jose Maria Nazar David,"[Jose Maria Nazar David, DAVID, JOSE MARIA, DA...",3640497501056163,UFJF,SUPPORTING AWARENESS IN GROUPWARE THROUGH AN A...,Michel Oei,JOURNAL OF UNIVERSAL COMPUTER SCIENCE,PERIODICO,2009,0948695X,139151
...,...,...,...,...,...,...,...,...,...,...,...
936713,Leandro Santiago de Araujo,"[Leandro Santiago de Araujo, L. S. ARAUJO, LEA...",6358983442870515,UFF,GERANDO BASE DE GRAFOS NÃO ISOMORFOS COM SEUS ...,Luís Felipe Ignácio Cunha,SBPO 2023: Simpósio Brasileiro de Pesquisa Ope...,CONFERENCIA,2023,None,76459
936714,Leandro Santiago de Araujo,"[Leandro Santiago de Araujo, L. S. ARAUJO, LEA...",6358983442870515,UFF,PARALELISMO E HEURÍSTICAS PARA O PROBLEMA DA M...,Thiago Lopes Nascimento,SBPO 2023: Simpósio Brasileiro de Pesquisa Ope...,CONFERENCIA,2023,None,112702
936715,Leandro Santiago de Araujo,"[Leandro Santiago de Araujo, L. S. ARAUJO, LEA...",6358983442870515,UFF,PARALELISMO E HEURÍSTICAS PARA O PROBLEMA DA M...,Fábio Protti,SBPO 2023: Simpósio Brasileiro de Pesquisa Ope...,CONFERENCIA,2023,None,112702
936716,Leandro Santiago de Araujo,"[Leandro Santiago de Araujo, L. S. ARAUJO, LEA...",6358983442870515,UFF,PARALELISMO E HEURÍSTICAS PARA O PROBLEMA DA M...,Luís Felipe Ignácio Cunha,SBPO 2023: Simpósio Brasileiro de Pesquisa Ope...,CONFERENCIA,2023,None,112702
936717,Leandro Santiago de Araujo,"[Leandro Santiago de Araujo, L. S. ARAUJO, LEA...",6358983442870515,UFF,PARALELISMO E HEURÍSTICAS PARA O PROBLEMA DA M...,Leandro Santiago de Araujo,SBPO 2023: Simpósio Brasileiro de Pesquisa Ope...,CONFERENCIA,2023,None,112702

## 2.3. Specifying temporal interval

In [16]:
df_productions = df_productions[(df_productions["year"] >= 2014) & (df_productions["year"] <= 2023)]
df_productions = df_productions.reset_index(drop=True)
df_productions

,name,citation,lattes_id,institution,production,authors,location,type,year,issn,production_id
0,Jose Maria Nazar David,"[Jose Maria Nazar David, DAVID, JOSE MARIA, DA...",3640497501056163,UFJF,SCIENTIFIC PROVENANCE METADATA CAPTURE AND MAN...,Wander Gaspar,"International Journal of Metadata, Semantics a...",PERIODICO,2015,17442621,129626
1,Jose Maria Nazar David,"[Jose Maria Nazar David, DAVID, JOSE MARIA, DA...",3640497501056163,UFJF,SCIENTIFIC PROVENANCE METADATA CAPTURE AND MAN...,Regina Maria Maciel Braga,"International Journal of Metadata, Semantics a...",PERIODICO,2015,17442621,129626
2,Jose Maria Nazar David,"[Jose Maria Nazar David, DAVID, JOSE MARIA, DA...",3640497501056163,UFJF,SCIENTIFIC PROVENANCE METADATA CAPTURE AND MAN...,Fernanda Cláudia Alves Campos,"International Journal of Metadata, Semantics a...",PERIODICO,2015,17442621,129626
3,Jose Maria Nazar David,"[Jose Maria Nazar David, DAVID, JOSE MARIA, DA...",3640497501056163,UFJF,SCIENTIFIC PROVENANCE METADATA CAPTURE AND MAN...,Jose Maria Nazar David,"International Journal of Metadata, Semantics a...",PERIODICO,2015,17442621,129626
4,Jose Maria Nazar David,"[Jose Maria Nazar David, DAVID, JOSE MARIA, DA...",3640497501056163,UFJF,SCIENTIFIC PROVENANCE METADATA CAPTURE AND MAN...,Tatiane Ornelas Martins Alves,"International Journal of Metadata, Semantics a...",PERIODICO,2015,17442621,129626
...,...,...,...,...,...,...,...,...,...,...,...
495575,Leandro Santiago de Araujo,"[Leandro Santiago de Araujo, L. S. ARAUJO, LEA...",6358983442870515,UFF,GERANDO BASE DE GRAFOS NÃO ISOMORFOS COM SEUS ...,Luís Felipe Ignácio Cunha,SBPO 2023: Simpósio Brasileiro de Pesquisa Ope...,CONFERENCIA,2023,None,76459
495576,Leandro Santiago de Araujo,"[Leandro Santiago de Araujo, L. S. ARAUJO, LEA...",6358983442870515,UFF,PARALELISMO E HEURÍSTICAS PARA O PROBLEMA DA M...,Thiago Lopes Nascimento,SBPO 2023: Simpósio Brasileiro de Pesquisa Ope...,CONFERENCIA,2023,None,112702
495577,Leandro Santiago de Araujo,"[Leandro Santiago de Araujo, L. S. ARAUJO, LEA...",6358983442870515,UFF,PARALELISMO E HEURÍSTICAS PARA O PROBLEMA DA M...,Fábio Protti,SBPO 2023: Simpósio Brasileiro de Pesquisa Ope...,CONFERENCIA,2023,None,112702
495578,Leandro Santiago de Araujo,"[Leandro Santiago de Araujo, L. S. ARAUJO, LEA...",6358983442870515,UFF,PARALELISMO E HEURÍSTICAS PARA O PROBLEMA DA M...,Luís Felipe Ignácio Cunha,SBPO 2023: Simpósio Brasileiro de Pesquisa Ope...,CONFERENCIA,2023,None,112702
495579,Leandro Santiago de Araujo,"[Leandro Santiago de Araujo, L. S. ARAUJO, LEA...",6358983442870515,UFF,PARALELISMO E HEURÍSTICAS PARA O PROBLEMA DA M...,Leandro Santiago de Araujo,SBPO 2023: Simpósio Brasileiro de Pesquisa Ope...,CONFERENCIA,2023,None,112702

In [17]:
preprocesser.write_parquet(df_productions, step="02-preprocessing", name="productions")